/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package quotes;

import com.google.common.reflect.TypeToken;
import com.google.gson.Gson;
import org.junit.jupiter.api.Test;

import java.io.BufferedReader;
import java.io.FileReader;
import java.io.IOException;
import java.util.ArrayList;

import static org.junit.jupiter.api.Assertions.*;

class AppTest {
//    @Test void appHasAGreeting() {
//        App classUnderTest = new App();
//        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
//    }
    @Test public  void check() throws IOException {
Gson gson=new Gson();

            FileReader file =new FileReader("src/test/resources/recentquotes.json");

            BufferedReader line= new BufferedReader(file);

            ArrayList<Qutes> obj=gson.fromJson(line,new TypeToken<ArrayList<Qutes>>(){}.getType());


            int random =(int) (Math.random()* obj.size());

            // System.out.println(obj.get(random));  This Method for lab08
            System.out.println(obj.get(0).author);// This Method using for testing


            line.close();

           String out ="Marilyn Monroe";


        assertEquals(out,obj.get(0).author);
    }

}
