/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package quotes;

import com.google.gson.Gson;
import com.google.common.reflect.TypeToken;
import java.io.BufferedReader;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        Gson gson = new Gson();
        try {
            FileReader file =new FileReader("recentquotes.json");

            BufferedReader line= new BufferedReader(file);

            ArrayList<Qutes> obj=gson.fromJson(line,new TypeToken<ArrayList<Qutes>>(){}.getType());


int random =(int) (Math.random()* obj.size());

            // System.out.println(obj.get(random));  This Method for lab08
            System.out.println(obj.get(5));// This Method using for testing


            line.close();

        } catch (IOException e) {
            e.printStackTrace();
        }


    }
}
