/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package quotes;

import com.google.gson.Gson;
import com.google.common.reflect.TypeToken;

import java.io.*;
import java.net.HttpURLConnection;
import java.net.MalformedURLException;
import java.net.URL;
import java.util.ArrayList;
import java.util.Arrays;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void apiDat(){
        String apiUrl="http://api.forismatic.com/api/1.0/?method=getQuote&format=json&lang=en";
        try {
            URL url= new URL(apiUrl);
            HttpURLConnection connection=(HttpURLConnection)url.openConnection();
            connection.setRequestMethod("GET");
            connection.setRequestProperty("User-Agent", "Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.11 (KHTML, like Gecko) Chrome/23.0.1271.95 Safari/537.11");

            int status = connection.getResponseCode();

            if(status == 200){
                InputStream inputStream= connection.getInputStream();
                InputStreamReader inputStreamReader = new InputStreamReader(inputStream);
                BufferedReader bufferedReader = new BufferedReader(inputStreamReader);
                String line ;

                StringBuilder lineBilder=new StringBuilder();
                line = bufferedReader.readLine();
                while (line != null){

                    lineBilder.append(line);

                    line = bufferedReader.readLine();
                    //if (line != null )
                }
                System.out.println(lineBilder);
                bufferedReader.close();
                FileWriter fw=new FileWriter("mydata.json");
                fw.write(String.valueOf(lineBilder));
                fw.close();
            }else {
                // if Error in connection it will call local Data file
               localData();
            }

            connection.disconnect();
        } catch (MalformedURLException e) {
            e.printStackTrace();
        } catch (IOException e) {
            e.printStackTrace();

        }
    }

    public static void localData(){
        Gson gson=new Gson();
//        System.out.println("An error occurred with API So we Reading Local Data status "+ status);
        FileReader file = null;
        try {
            file = new FileReader("recentquotes.json");
        } catch (FileNotFoundException e) {
            e.printStackTrace();
        }
//
        BufferedReader line= new BufferedReader(file);

        ArrayList<Qutes>  obj=gson.fromJson(file,new TypeToken<ArrayList<Qutes>>(){}.getType());
        int random =(int) (Math.random()* obj.size());
//
        System.out.println(obj.get(random));
    }

    public static void main(String[] args) {

        // Call function ApiDat  if status not 200 the method will call local data Method inside apiData

        apiDat();

    }
}
